# Generated by Django 6.0.7 on 2026-07-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='id_students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='pages.students'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='id_students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='pages.students'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='id_subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='pages.subjects'),
        ),
        migrations.AlterField(
            model_name='students',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='pages.classes'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id_teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='pages.teachers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
