# Generated by Django 6.0.7 on 2026-07-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_students_subjects_teachers_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absences',
            old_name='age',
            new_name='justifie',
        ),
    ]
