# Generated by Django 6.1 on 2026-08-31 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_absences_id_students_alter_grades_id_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grades",
            name="id_students",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="pages.students",
            ),
        ),
        migrations.AlterField(
            model_name="grades",
            name="id_subjects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="pages.subjects",
            ),
        ),
    ]
