# Generated by Django 6.0.7 on 2026-07-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_age_absences_justifie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absences',
            old_name='justifie',
            new_name='status',
        ),
    ]
